### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by ssciarini** [fmeringdal/rust_rrule#10]
First, thank you for putting together this library! It has been a great help for a "magic mirror" type project I am working on at home. 

I am pulling down my google calendar and having pretty good success with this, but ran in to a rule that parses fine but will not return. I've included an example below.

```rust
use chrono::prelude::Local;
use rrule::RRule;

fn main() {
    let rrule = "DTSTART:20200427T090000\nFREQ=WEEKLY;UNTIL=20200506T035959Z;BYDAY=FR,MO,TH,TU,WE"
        .parse::<RRule>()
        .unwrap();
    let instances: Vec<_> = rrule
        .into_iter()
        .skip_while(|d| *d < Local::now())
        .take(2)
        .collect();
    println!("{:?}", instances);
}
```

```
[dependencies]
chrono = "^0.4.19"
chrono-tz = "^0.5.3"
rrule = "^0.5.2"
```

I would expect the code above would just print out an empty Vec, but instead it just hangs. Any thoughts? Thanks again!

**Comment by fmeringdal** [comment]
Hi, thank you for reporting this issue and using this library!
I have solved this issue now and will soon release a new version (0.5.3) with the fix :)

**Comment by fmeringdal** [comment]
New version released now with this bug fixed. Feel free to reopen if this issue persist :)
