### ISSUE TITLE
Add frequency "once"?

### ISSUE THREAD

**Issue by teymour-aldridge** [fmeringdal/rust_rrule#11]
I'm happy to submit a patch for this, I just want to check if this would be wanted?

I think it would then make sense to use this as the default behaviour, and if `FREQ=""` is not defined, to just use this instead.

(I don't know if this deviates from the spec though)

**Comment by fmeringdal** [comment]
Hi, according to the RFC there is no frequenzy equals to once. But you have the `count`  attribute which you can set to one and I think that is what you want here?

**Comment by teymour-aldridge** [comment]
Oh my bad :D 

Yup I think that's what I want :)

Thanks writing this library
