### ISSUE TITLE
RRULE with bi-weekly recurrence has the wrong final instance

### ISSUE THREAD

**Issue by aggregat4** [fmeringdal/rust_rrule#13]
I have a meeting (ical generated by Exchange) that has an RRULE that fails to generate a recurrence for today (8th of March 2021) although I think it should. The Outlook Web Calendar shows an event for today. 

Interesting is that the rule ends on the 8th of March, but according to the ical RFC UNTIL is inclusive.

here is the failing test, I have added the final date being generated as a comment:

```
    #[test]
    fn rrule_generates_final_event_on_8_3_2021() {
        let dates = "DTSTART;TZID=W. Europe Standard Time:20201214T093000\nRRULE:FREQ=WEEKLY;UNTIL=20210308T083000Z;INTERVAL=2;BYDAY=MO;WKST=MO\nEXDATE;TZID=W. Europe Standard Time:20201228T093000,20210125T093000,20210208T093000".parse::<RRuleSet>().unwrap().all();
        // the following outputs 2021-02-22 09:30:00 UTC
        println!("last date: {}", dates[dates.len() - 1]);
        assert_eq!(8, dates[dates.len() - 1].day());
        assert_eq!(3, dates[dates.len() - 1].month());
        assert_eq!(2021, dates[dates.len() - 1].year());
    }
```

**Comment by fmeringdal** [comment]
Hi,
The start datetime has time 09:30 while the endtime has time 08:30 and they both have the same timezone (UTC= West Europe Time), so I am not sure what you mean by inclusive, could you clarify?

**Comment by aggregat4** [comment]
The DTSART is 9:20 in Western European Time, but the end time is UTC, where 8:30 is actually the same as 9:30 Western European time.

I already have a ticket where I ask for timezone support in rrule. At the moment I just strip all timezones and let rrule calculate everything in UTC. But I just realized that I should then also convert the DTSTART to UTC before feeding it to rrule.

**Comment by fmeringdal** [comment]
Ok, so now I understand the problem.
RRule does support timezones, but they have to be specified as an IANA timezone format.
For example your test is passing if the timezone is rewritten as `Europe/Paris`:

```rust    
#[test]
fn rrule_generates_final_event_on_8_3_2021() {
        let dates = "DTSTART;TZID=Europe/Paris:20201214T093000\nRRULE:FREQ=WEEKLY;UNTIL=20210308T083000Z;INTERVAL=2;BYDAY=MO;WKST=MO\nEXDATE;TZID=Europe/Paris:20201228T093000,20210125T093000,20210208T093000".parse::<RRuleSet>().unwrap().all();
        // the following outputs 2021-02-22 09:30:00 UTC
        println!("last date: {}", dates[dates.len() - 1]);
        assert_eq!(8, dates[dates.len() - 1].day());
        assert_eq!(3, dates[dates.len() - 1].month());
        assert_eq!(2021, dates[dates.len() - 1].year());
}
```

**Comment by aggregat4** [comment]
I really wish I could assume IANA identifiers for timezones, sadly that's not how it is in the real world. Would it be sensible for rrule to at least not silently accept this? Maybe return an error when the timezones do not match?

**Comment by fmeringdal** [comment]
Yes, timezones are really a pain in the ass to work with and many timezones in the real world coming from different applications seems to be specified in a non-standard format (if any format at all).

I hope to be able to provide support for fixed time zone format (e.g. `UTC+7`) in addition to IANA format to rrule soon, but except from that it is nearly impossible to know which format a given timezone string is (for example `W. Europe Standard Time` doesnt seem to follow any standard format).

Anyways, you are absolutely correct in that rrule shourt return an `Err` when time zone is invalid and not just blindly accept it. I will look into that as well.

**Comment by fmeringdal** [comment]
#23 Replaces this issue. Feel free to reopen
