### ISSUE TITLE
Date parsing fails when explicit timezone identifier string is present

### ISSUE THREAD

**Issue by aggregat4** [fmeringdal/rust_rrule#3]
Using rrule 3.4.0 and doing the following test:

```
 #[test]
    fn rruleset_parsing_date_with_timezone() {
        "DTSTART;TZID=\"(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna\":20201111T160000\nRRULE:FREQ=WEEKLY;UNTIL=20210428T140000Z;INTERVAL=6;BYDAY=WE;WKST=MO".parse::<RRuleSet>().unwrap();
    }
``` 

causes the error:

```
thread 'meeters_ical::tests::rruleset_parsing_date_with_timezone' panicked at 'called `Result::unwrap()` on an `Err` value: RRuleParseError("Invalid datetime: 00)")', src/meeters_ical.rs:310:195
```

**Comment by fmeringdal** [comment]
Right now this crate only has support for timezones that are specified in the [IANA database](https://www.iana.org/time-zones). But the goal is certainly to be able to support other timezone formats as well. I will put some effort into supporting fixed offset timezone strings (like the one you provided), and hope to have it ready for v.3.5.0.

**Comment by aggregat4** [comment]
Much appreciated! I know the pain with this date parsing since in the application I'm writing using your library I was already parsing dates and it is kind of stupefying how many variants the ical spec allows.

Do you think it may be useful to split out the date parsing bits into some common library?

**Comment by fmeringdal** [comment]
Yeah there is certainly a lot of complexity to parsing all the different kinds of ical strings. 
Both the chrono and chrono-tz crates help a lot with parsing dates, datetimes and timezones (IANA timezone) from strings. Actually it is not that much work needed to parse the timezone strings that are not supported by chrono-tz (some new regex will get the job done), so I think it is okay to just keep all of the string parsing stuff within this crate.

**Comment by aggregat4** [comment]
@fmeringdal  do you know of a good workaround for specifying the timezone? I can preprocess the ical, but just stripping the timezone causes alls dates to be UTC. Is there an alternative way to indicate the timezone that your library supports?

**Comment by fmeringdal** [comment]
@aggregat4 I am still not sure how to convert between the _Tz enum_ (provided by chrono-tz) that I use internally in this crate and a given UTC offset that I get from parsing the rrule string. My plan is to take a deeper look into all of this this weekend or the next. Please let me know if you have some ideas on how to do this!

**Comment by fmeringdal** [comment]
#24  Replaces this issue. Feel free to reopen
