### ISSUE TITLE
Montly recurrence on first wednesday yields wrong result in rrule

### ISSUE THREAD

**Issue by aggregat4** [fmeringdal/rust_rrule#5]
The following rule expresses that an appointment happens _only_ on the first wednesday of each month:

```
DTSTART;VALUE=DATE:20200701\nRRULE:FREQ=MONTHLY;UNTIL=20210303T090000Z;INTERVAL=1;BYDAY=1WE
``` 

When parsed with rrule I get a weekly occurence (_every_ wednesday).

**Comment by fmeringdal** [comment]
Great catch, fixed this now! Will release in 0.3.6 later today
