### ISSUE TITLE
Parse RRule without DTSTART

### ISSUE THREAD

**Issue by raventid** [fmeringdal/rust_rrule#6]
Hey, thank you for work on rrule library!

According to https://jakubroztocil.github.io/rrule/ RRULE could be parsed without explicit DTSTART to express recurrence pattern. Now, this scenario is not covered (if I am not missing something)

```rust
let mut rrule: RRule = "FREQ=DAILY;COUNT=7".parse().unwrap();

thread 'test' panicked at 'called `Result::unwrap()` on an `Err` value: RRuleParseError("Invalid datetime: FREQ=DAILY;COUNT=7")',
```

**Comment by fmeringdal** [comment]
Thank you for using this library!
This is now supported in version 0.3.7, please let me know if you find other bugs or enhancements missing.

**Comment by raventid** [comment]
Will do 👍 

Keep up the great work!
