### ISSUE TITLE
Add support for manual recurrence rule changes

### ISSUE THREAD

**Issue by aggregat4** [fmeringdal/rust_rrule#7]
When someone makes a manual change to a recurrence it appears to be modeled as new VEVENTs that have the same UID and SEQUENCE of a particular VEVENT with an RRULE and additionally there is a RECURRENCE-ID that identifies one particular instance of that recurrence that was modified. This modified event then supersedes the one that would have been generated from the RRULE.

As an example I created an empty calendar (in Outlook Web Access) and defined a weekly recurring event (no end date) on Fridays at 14:00, starting on the 18th of December.

Then I moved the second instance of this recurrence (the event on Friday the 25th of December) manually to the Wednesday before (the 23rd) at 10:00.

There appears to be a readable explanation of some aspects of this at [icalevents.com](https://icalevents.com/4437-correct-handling-of-uid-recurrence-id-sequence/),

The following ICS file was generated from this (I added the newlines between the VEVENTs):

``` 
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Testcal
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE

BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=WEEKLY;UNTIL=20210618T120000Z;INTERVAL=1;BYDAY=FR;WKST=MO
UID:040000008200E00074C5B7101A82E00800000000857ED29414D5D601000000000000000
 0100000005976D1BBA755D145B165875C69398A49
SUMMARY:Test Weekly Recurrence
DTSTART;TZID=W. Europe Standard Time:20201218T140000
DTEND;TZID=W. Europe Standard Time:20201218T150000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20201218T080644Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

BEGIN:VEVENT
DESCRIPTION:\n
UID:040000008200E00074C5B7101A82E00800000000857ED29414D5D601000000000000000
 0100000005976D1BBA755D145B165875C69398A49
RECURRENCE-ID;TZID=W. Europe Standard Time:20201225T140000
SUMMARY:Test Weekly Recurrence
DTSTART;TZID=W. Europe Standard Time:20201223T100000
DTEND;TZID=W. Europe Standard Time:20201223T110000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20201218T080644Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
```

**Comment by fmeringdal** [comment]
This library aims to implement the rrule section of the iCalendar RFC. This feature is not part of the RFC, since it deals with combining multiple recurrence rules to model the feature correctly.

I think the correct approach here is for this library to just concern itself with the rrule aspect and leave it to the application to implement features that needs to combine different rrules to be modelled correctly. It should be quite straightforward for the application to implement this given the rrule abstracration provided by this library.
Feel free to reopen the issue if you want to discuss this further.

**Comment by aggregat4** [comment]
You are absolutely right, now that I think about it, this is a level on top of the rrule library. Makes total sense to keep it out. I think I can easily accommodate this in my application.
